const checks=[
 {title:'Is the device connected to the network?',desc:'Look at the Wi-Fi or Ethernet indicator. We are checking the device’s local connection before testing anything farther away.',command:'ipconfig /all',pass:'The device has a local link. Next, test whether it can reach the local network.',fail:'The break is at the device layer. Reconnect Wi-Fi, check the cable, or enable the network adapter, then test again.',fix:'Reconnect to the correct network and confirm the adapter is enabled.'},
 {title:'Did the device receive a valid IP address?',desc:'In the output, find the IPv4 address. An address like 169.254.x.x usually means the device could not reach DHCP.',command:'ipconfig',pass:'The device has an address to use. Next, test its route to the local gateway.',fail:'No valid address was assigned. DHCP, the Wi-Fi network, or a static configuration may be involved.',fix:'Renew the lease with ipconfig /release then ipconfig /renew.'},
 {title:'Can it reach the default gateway?',desc:'The gateway is the first hop out of the local network. A reply proves the local path is working.',command:'ping <default-gateway>',pass:'The local path is responding. Next, check name resolution and the wider network.',fail:'The device can’t reach the local router. Look at the access point, VLAN, cable, or gateway.',fix:'Check the AP/switch link and confirm the gateway matches the network.'},
 {title:'Can it reach an IP on the internet?',desc:'Use a known public IP to separate routing problems from DNS problems. This test does not need a hostname.',command:'ping 1.1.1.1',pass:'Internet routing works. If websites still fail, DNS or the browser path is the likely layer.',fail:'Traffic cannot leave the local network. Check the router, firewall, or ISP path.',fix:'Verify the router’s WAN status and firewall policy.'},
 {title:'Can DNS resolve a hostname?',desc:'Now test the translation from a name to an IP address. This is the check that makes “websites won’t load” concrete.',command:'nslookup example.com',pass:'DNS is responding. Try the browser, proxy, or the specific service next.',fail:'Names are not resolving. The configured DNS server or its path is the likely cause.',fix:'Check DNS settings, then test a known internal or public DNS server.'},
 {title:'Does the service itself respond?',desc:'The network may be healthy even when one website or application is down. Test the specific destination and port.',command:'curl -I https://example.com',pass:'The service responds. Document the evidence and close the ticket.',fail:'The destination or service may be down, blocked, or misconfigured. Escalate with your evidence.',fix:'Check service status and proxy/firewall logs; include every successful check in the escalation.'}
];
let current=0,answered=0;
const $=id=>document.getElementById(id);
function render(){const c=checks[current];$('stepNumber').textContent=String(current+1).padStart(2,'0');$('stepStatus').textContent=`CHECK ${current+1} OF ${checks.length}`;$('checkTitle').textContent=c.title;$('checkDescription').textContent=c.desc;$('checkCommand').textContent=c.command;$('stepLineFill').style.width=`${((current+1)/checks.length)*100}%`;document.querySelectorAll('.layer').forEach((el,i)=>el.classList.toggle('active-layer',i===Math.min(2,Math.floor(current/2))));}
document.querySelectorAll('.answer-btn').forEach(btn=>btn.addEventListener('click',()=>{const c=checks[current],ok=btn.dataset.answer==='pass';if(!ok){showToast(`Likely fix: ${c.fix}`)}else{showToast(c.pass);if(current<checks.length-1){answered=Math.max(answered,current+1);current++;render()}else{answered=6;showToast('Case complete — nice work. Document the evidence.')}}$('progressPercent').textContent=`${Math.round(((6+answered)/25)*100)}%`}));
$('copyBtn').addEventListener('click',()=>{navigator.clipboard?.writeText($('checkCommand').textContent);showToast('Command copied')});$('resetBtn').addEventListener('click',()=>{current=0;answered=0;render();$('progressPercent').textContent='24%';showToast('Case reset')});
document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));item.classList.add('active');const view=item.dataset.view;$('labView').classList.toggle('hidden',view!=='lab');$('conceptsView').classList.toggle('hidden',view!=='concepts');$('commandsView').classList.toggle('hidden',view!=='commands')}));
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}render();
